/** Maps a stored metering event and its publication status to the metering_events table. */
package com.platform.entitlements.metering;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Read-side representation of a metering event row. Rows are actually
 * INSERTed via MeteringEventDao (raw JDBC, so we can use
 * INSERT ... ON CONFLICT ... RETURNING — not expressible through a plain
 * JPA save()). This entity exists so we can look up an existing row
 * (on the duplicate-request path) and so the reconciliation job can query
 * and update `published_at` through normal JPA.
 */

// 1. ORM MAPPING
// @Entity marks this as a database model managed by Hibernate.
// @Table links this class directly to the 'metering_events' table in PostgreSQL.
@Entity
@Table(name = "metering_events")

// 2. LOMBOK BOILERPLATE REDUCTION
// Automatically generates all getters, setters, and a default constructor at compile-time.
@Getter
@Setter
@NoArgsConstructor
public class MeteringEvent {

    // Primary Key (UUID generated by PostgreSQL during insert)
    @Id
    private UUID id;

    // 3. IMMUTABLE AUDIT FIELDS (updatable = false)
    // Telling Hibernate 'updatable = false' ensures that even if a developer 
    // accidentally changes these values in Java code, Hibernate will NEVER 
    // include them in an UPDATE SQL statement. Usage history is permanent.

    @Column(name = "tenant_id", nullable = false, updatable = false)
    private UUID tenantId;

    @Column(name = "idempotency_key", nullable = false, updatable = false)
    private String idempotencyKey;

    @Column(name = "event_type", nullable = false, updatable = false)
    private String eventType;

    @Column(nullable = false, updatable = false)
    private BigDecimal quantity;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    // 4. MUTABLE EVENT-PUBLISHING FIELDS
    // Unlike the fields above, these two fields CAN be updated by background jobs.
    // They track whether this event has been published to external messaging systems (e.g. EventBridge).

    // Timestamp when the event was successfully sent to the message broker (null = not published yet)
    @Column(name = "published_at")
    private Instant publishedAt;

    // Tracks retries if publishing fails, preventing infinite retry loops
    @Column(name = "publish_attempts", nullable = false)
    private int publishAttempts;
}